### ISSUE TITLE
List of new features to implement in NoiseCraft

### ISSUE THREAD

**Issue by maximecb** [maximecb/noisecraft#1]
This is a meta-issue to help spur discussion and organize contributions. The list of features below is based on things that were the most requested by users. Most of them are designed to reduce friction. The killer feature of NoiseCraft will be grouping, which will allow users to create new custom modules that can be reused. This will allow project to scale to much larger sizes much easier. For example, users could create a reusable stereo delay module, a 4-channel mixer, or a kick or snare sound modules that other users can then copy and paste into their own projects.

Tentative list:
- [x] Select and move multiple nodes at once
- [x] Delete one or more selected nodes
- [x] Undo
- [x] Redo
- [x] Ability to group nodes into custom user-created modules
- [x] Ability to save projects into local files
  - Local saving would allow people to easily run local instances, or implement tools
  - Fosters more user trust than having us own their data
- [x] Edges should have different colors to make them easier to follow visually
- [x] Edges could potentially be curved lines, improve visibility
- [x] Copy and paste one or more selected nodes
  - We probably want to design this so we could copy and paste from another project. That would require using the paste buffer API.
  - Module (group) nodes will have to be copied recursively so all nodes inside get a unique id
- [x] Minimize audio glitches by rendering audio in a background thread
- [ ] Ability to expose knobs inside custom modules in the UI
  - If you group multiple nodes, some of the nodes you group could be knobs, you would then be able to pick which knobs will be visible in your new custom module node
- [ ] Light node that flashes when the incoming signal is `> 0`. This is like a little LED indicator.
  - The color of each light could be user-configurable.
- [ ] GateSeq (gate sequencer) with one separate gate output for each row in the sequencer.
  - This will make it much easier to build something like a drum machine.
- [ ] Polyphonic MIDI input node
  - Can have a node config option to control the number of voices exposed
  - Each voice gets its own gate/trigger. Just connect multiple voice modules.
- [x] Implement new Browse page (i.e. `/browse`)
- [x] Implement new Help page
- [ ] Implement terms of service page
  - Have people agree when creating an account
  - Should protect ourself, no warranty, potential risk of data leaks, etc.

**Comment by maximecb** [comment]
I just made the GitHub repo public in prevision of an eventual public release. Should also help with recruiting collaborators.

**Comment by alexlitty** [comment]
Awesome!! Hello, world :)

**Comment by maximecb** [comment]
I'm going to close this issue for now because we're probably better off with multiple individual issues.
