### ISSUE TITLE
WebAudioModule 2 support?

### ISSUE THREAD

**Issue by boourns** [maximecb/noisecraft#103]
Hello from another Shopify alumni!

I'm wondering if you've considered supporting, or are aware of, WebAudioModule 2 plugins.  They are ES6 modules loaded at runtime conforming to a standard that allow audio plugins to interoperate across audio hosts.  WAMs support automation, MIDI, audio, and through an extension, webgl2 video.

Some references to learn more in case you're interested:

https://wam-examples.vidalmazuy.fr/example3/index.html - probably the best introduction to working with WAMs
https://github.com/boourns/wam-community - a collection of ~40 ready-to-use WAM2 plugins published on NPM
https://github.com/webaudiomodules/sdk - the SDK

If you want to try the WAMs in wam-community I can suggest my WAM host I've been working on for the past few years - https://sequencer.party

Regards,
Tom

**Comment by maximecb** [comment]
At the moment I'd rather keep noisecraft simple. I don't want to integrate with plugins because the risk of breakage seems high.
