### ISSUE TITLE
Coloring edges originating from a src port

### ISSUE THREAD

**Issue by alexlitty** [maximecb/noisecraft#11]
Depends on #12. Prior discussion in [this comment](https://github.com/maximecb/noisecraft/pull/8#issuecomment-866506706).

Set the "correct" color for edges that originate from a src port.

Edges colors are determined by the src port they come from. If you start creating an edge connection from a src port, we already know what color that edge will be.

Currently however, we purposely keep the color gray until the edge is connected on both src and dst ends. It serves as visual feedback for the connection being made. If we can find an alternative feedback mechanism in #12, we can implement this without losing visual feedback.

**Comment by maximecb** [comment]
Closing this for now.
