### ISSUE TITLE
Blue cables not visible enough on darkmode

### ISSUE THREAD

**Issue by loatus** [maximecb/noisecraft#110]
Hi Maxime ,

I am having a problem with not being able to see the ' blue cable against the dark mode background.. I like dark mode but prefer the yellow , red , green cables for visibility.. perhaps a pink cable could be used instead.

I am alternating between the chrome browser and the Opera browser and the blue cable is near invisible on both. perhaps a pink or greeny yellow  distinct enough from the existing yellow and green/ teal could replace the blue cable.

 thanks for the great app,

Dan

**Comment by maximecb** [comment]
Hi Daniel!

I've listened to all of the projects that you posted. I enjoy them very much :)

I am on a macbook air, and to me the blue cables appear very sharply contrasting against the dark grey background. Would you be willing to share what kind of display you are using (laptop/desktop/brand)? I am wondering if your display has very low contrast, or if maybe you are color blind (many people are but do not know)? Another possibility is that maybe you are on a mac and you have "true tone" enabled in your settings, which can mess with colors? 

I can try to make the dark grey background a bit darker, and to make the blue cable brighter to increase the contrast some more. I could also try to inject some red into the blue color.

Just to be clear: you mean the bright blue color? There are also teal (blue-green) colored cables, can you see those well?

**Comment by loatus** [comment]
Hi Maxime ,

Thankyou for your appreciation and kind words! and also getting back to me on this issue promptly. 

I have just realised that I have a blue blocking filter, which I had forgotten about ( an app called 'f.lux', maybe you've heard of it ) ,which comes into effect in the evenings when I tend to use Noisecraft. Without 'f.lux' the bright blue appears as it should , with sufficient contrast and perfectly visible. interestingly when 'f.lux' is turned on , the neon or bright blue becomes hardly visible but the teal is still very visible. also the pink becomes near indistinguishable from the red. So as long as I have ' f.lux' off , I can see the blue cables fine.  So as far as I am concerned the issue is more or less fixed.   I hope this helps . Thanks again. 

Dan

**Comment by maximecb** [comment]
No worries I'm glad it's working :)
