### ISSUE TITLE
Alternative feedback for edge connections

### ISSUE THREAD

**Issue by alexlitty** [maximecb/noisecraft#12]
Prior discussion in [this comment](https://github.com/maximecb/noisecraft/pull/8#issuecomment-866506706).

When an edge connection is created (the moment you click on the "other" port to finalize the connection) there is some visual feedback: The edge color changes from gray to a different non-gray color.

It would be nice to introduce a different kind of visual feedback here, one that doesn't depend on the color, as we'd like to introduce another feature (#11) that conflicts with this.

**Comment by maximecb** [comment]
Closing this for now.
