### ISSUE TITLE
Autoscroll when moving nodes outside of window

### ISSUE THREAD

**Issue by maximecb** [maximecb/noisecraft#17]
The editor div will automatically resize to fit all nodes, both when a project is loaded and when nodes are moved outside of the window (see `Editor.resize()` method). However, ideally, we'd also like to automatically scroll horizontally and vertically to "follow" nodes when they are moved outside the window.

One additional difficulty is that we want to avoid the scrolling going crazily fast when nodes are moved outside the window/viewport. We need this to work smoothly. Probably, we should scroll by the exact number of pixels that a node gets pushed outside the window.

There's an added little wrinkle here that scrolling is going to mess with the way the getMousePos() method operates, because it tries to calculate a position relative to the editor div, whereas for the scrolling, what we really want is deltaX, deltaY in the mouse movement.

**Comment by alexlitty** [comment]
This has proven quite tricky!

It's straightforward to autoscroll into the right and bottom directions at any point (adjusting `scrollTop` and `scrollLeft` as a node is being moved), but I'm having trouble coming up with a good solution for the left and top directions when the user is at the far left or far top of the editor; `scrollTop` and `scrollLeft` can't be negative, so we can't simply adjust those properties into the negative direction.

What do you think about implementing this incrementally, adding autoscrolling in non-negative spaces first?

**Comment by maximecb** [comment]
Yes that's totally fine. I don't think we want to scroll into negative space.
