### ISSUE TITLE
Handling multiple pastes in a row

### ISSUE THREAD

**Issue by alexlitty** [maximecb/noisecraft#18]
When you have some nodes copied and you paste them multiple times without moving the cursor, the pasted nodes will always be in the same position.

Pasting is "working as intended" in a sense, but it's difficult to see these new nodes that are 100% overlapping with the old ones.

@maximecb was suggesting we could paste everything with some jitter: On every paste, the final position of the pasted nodes would all be moved +/-5px or so.

Another idea is to detect many identical pastes have happened at the same location in a series, then shift them accordingly. For example: On the first paste, leave them as they are. On the second paste, x+=10 and y+=10. On the third paste, x+=20 and y+=20. On the Nth paste, x+=((N-1)*10) and y+=((N-1)*10).

**Comment by maximecb** [comment]
I'm going to close this one for now because it's not a priority.
