### ISSUE TITLE
no sound when play is not pressed

### ISSUE THREAD

**Issue by severak** [maximecb/noisecraft#31]
I started new module and added few nodes to make basic MIDI synth. It did not make any sound at all.

I found out, that I need to press play to enable sound.

There should be some popup when you try to play midi on your keyboard and sound is stopped.

**Comment by maximecb** [comment]
That could be a good idea.

**Comment by ManuLintz** [comment]
Hi! I'd be really happy to work on this issue

**Comment by maximecb** [comment]
Hello Manu! Sure. Might make sense to produce a popup using the `Dialog` class when someone presses a MIDI key while playback is not active. Might be possible to put the logic for that outside of the editor, by adding a listener for MIDI events (see `midi.addListener`). Ideally the popup should show up only once per session.

Would also make sense to update the /help page, maybe add a first section about producing sound to the /help page under "The Basics".

**Comment by maximecb** [comment]
Actually, we probably want to show the popup when keys on the keyboard are pressed as well, not just MIDI keys 🤔

**Comment by ManuLintz** [comment]
Ok thanks for the precisions.

Showing the popup when keys on the keyboard are pressed seems like a good idea
