### ISSUE TITLE
an extra option with the waves ... 0 to 1.... or  -1 to 1

### ISSUE THREAD

**Issue by loatus** [maximecb/noisecraft#45]
I am enjoying your app a lot. I would quite like an option with the wave types where I could select a zero to 1 range at a click so that I wouldn't have to add  and divide to achieve the same thing. I realize that part of your intentions may be about keeping the user interface as simple as possible encouraging creative solutions to such things. I do find myself repeating this process enough that I think it would be of value and help to lay down ideas more easily.  Thanks for the great software :)

**Comment by maximecb** [comment]
Hi Daniel. Very happy to hear you're enjoying the app :)

Currently if you double-click on the sine node, you can set `minVal` and `maxVal` parameters. Would adding that to the other oscillator types (Tri, Pulse, Saw) satisfy your use case, or were you thinking something else?

**Comment by loatus** [comment]
I didn't realize you could do that with sines.. maybe i have used this
feature before but forgotten. Yeah if you could make the other wave types
have the same min/ max value parameters that would be great.
 I don't want to pester you with suggestions , but one more would be that
the clickable input/ output ports be a tiny bit bigger or as big as can be
allowed  as I find myself clicking and dragging repeatedly attempting to
pull/ connect a cable from a port and I am assuming it is because i am not
being accurate enough in my mouse cursor placement when this occurs. not a
big thing though. Anyways, thanks again

**Comment by maximecb** [comment]
It's done, added minVal/maxVal parameters to all oscillator types :)
