### ISSUE TITLE
Server configuration proposal

### ISSUE THREAD

**Issue by victorKochkarev** [maximecb/noisecraft#54]
Currently, the application can run only on port HTTP 7773 and would use file .database.db as its database file.

It can cause problems for users/environments that, for some reason, don't have port 7773 available. As well ability to change database file name might improve development or runtime flexibility.

I would propose to implement an ability to use environment variables so a user/developer could define an alternative HTTP port or any alternative DB file name. If no, params will be provided - current values will be used by default.

And again - will be happy to work on it.

**Comment by victorKochkarev** [comment]
Done - tried to keep it as simple as it is possible:
https://github.com/maximecb/noisecraft/pull/56

**Comment by maximecb** [comment]
Thank you :)
