### ISSUE TITLE
shift-click-to-delete causing frustration

### ISSUE THREAD

**Issue by treefrogman** [maximecb/noisecraft#59]
the issue is most notable in the notes node. when editing text, it is instinctual to shift-click in the text to select everything from the text cursor to the mouse cursor. unfortunately this action instead irretrievably annihilates the node and all the notes that were written.

moreover, though, shift-clicking is not normally a delete action, at least not in any of the guis i have used before.

i would love to see shift-click-to-delete retired altogether, since the delete key already serves that function. it would make sense to me to instead enable click-selection of nodes, allowing deletion of individual nodes with the same number of user actions as the current method ([click, delete] instead of [shift-click]).

optionally the X key could be added as an alias for delete, as it is a more reachable key (like shift) and it is familiar to users of Blender's node programming system.

**Comment by maximecb** [comment]
I'll look to see if clicking on nodes to select is easy to implement.

In the meantime I changed the code to stop the click on the text area of Notes from propagating, so it should help with the issue you were experiencing.

**Comment by treefrogman** [comment]
thank you!!

**Comment by maximecb** [comment]
It is done. Nodes can now be selected with a single click, and shift+click to delete has been retired :)
