### ISSUE TITLE
Colored SVG Play / Stop buttons

### ISSUE THREAD

**Issue by maximecb** [maximecb/noisecraft#62]
Right now there's a Play/Stop button in the top right corner of the app. However, it's just a text link and it's not very noticeable. That means new users often miss it and are left wondering why no audio is being produced.

I think it would make sense to have a green Play button that says "Play ▶" with the right-facing triangle next to it. This button should be replaced by a red "Stop □" button when playback is started.

The play and stop button graphics should preferably be in SVG format and should have exactly the same width and height.

**Comment by fakoredeDamilola** [comment]
Hey I will like to try this,

**Comment by maximecb** [comment]
Hey @fakoredeDamilola. That would be awesome 👍  Please keep us updated on your progress :)

**Comment by fakoredeDamilola** [comment]
Hello, please can you help me with this error. This occurs when I run npm start
![image](https://user-images.githubusercontent.com/47531232/148174893-28679e76-9d49-4a9e-a1b1-0eb66c92c30e.png)

**Comment by maximecb** [comment]
So it turns out installing node on windows seems to be challenging: #63 

I think that on windows, the easiest solution is probably to try and run using docker: https://github.com/maximecb/noisecraft#running-using-docker

**Comment by maximecb** [comment]
Another user was able to get it working on Windows using Docker.
