### ISSUE TITLE
Investigate why knobs don't work in Safari

### ISSUE THREAD

**Issue by maximecb** [maximecb/noisecraft#65]
I'm able to change knob values in Chrome and Firefox but not Safari.

Example:
https://noisecraft.app/101

**Comment by DI-john** [comment]
@maximecb Noticed that Safari doesn't receive the expected movementY values on these mouse events, here is a possible workaround:

https://github.com/maximecb/noisecraft/pull/67

**Comment by maximecb** [comment]
Thanks for taking a look DI-John. I tried out your fix and it seems to work, but I'm a bit confused because.

1. The [MDN page](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/movementY) lists Safari as supporting `MouseEvent.MovementY`, but in actuality, my Safari browser reports the value as always being zero (wtf?). So your fix seems to work, but it seems like it shouldn't be needed?

2. There's another bug in Safari. When the mouse is released, it triggers the node creation dialog. This should not be happening because of the pointer capture. This is more wacky behavior on the part of Safari, which I'm not sure how to address, besides maybe using an invisible div or something?

**Comment by DI-john** [comment]
@maximecb 

> The MDN page lists Safari as supporting MouseEvent.MovementY, but in actuality, my Safari browser reports the value as always being zero (wtf?)

Yeah, that's what I encountered as well.  Perhaps it's a browser bug that only happens in the context of the `setPointerCapture` / `releasePointerCapture`.  Might be interesting to do some tests using the movementY value in various contexts, perhaps it works just in a regular onmousemove handler without pointer capture.

> There's another bug in Safari. When the mouse is released, it triggers the node creation dialog.

Hm, interesting.

**Comment by maximecb** [comment]
I merged #69 from DI-John. This sidesteps the bug in Safari and the knobs now work. There's another issue with pointer capture seemingly not working in Safari (argh wtf!), but the situation for Safari users has improved.

I'll still leave the warning popup suggesting that Safari users should use Chrome enabled, at least until we have a fix for the pointer capture bug.

**Comment by maximecb** [comment]
Pushed a hack which should fix this problem.
