### ISSUE TITLE
Separate Data from Structure

### ISSUE THREAD

**Issue by wdevore** [maximecb/noisecraft#66]
Would anyone consider the idea of separating _Data_ from _Structure_. An example to create a new node **Configurations** that contained a list of **radio buttons**+**labels** where each row would switch between data sets without needing to remember all the settings of each node, or needing to create separate project for each settings arrangement. This new node would save with the project json and thus stay with the project.

Any thoughts or interest into separating _Data_ from _Structure_?

**Comment by maximecb** [comment]
So if I get your idea, you're talking about having a kind of preset mechanism. What I don't love about this is that, in addition to adding complexity to the system, it would be able to change a bunch of hidden parameters in many places at once. Currently, the way to achieve what you want is to copy a project and change the settings. You could also fade different voices in and out with knobs, or we could add a new node that allows switching between two separate inputs.

**Comment by wdevore** [comment]
Yes you understand correctly ;-). The new node you are suggesting is indeed along the lines of what I was inferring, but your suggestion is more visual which certainly fits the application. My I suggest a slight modification to that new node in that it has a knob that provides switching between N number of inputs and or outputs. Or perhaps a node that acts as a router of sorts and that is controlled by an input-value for routing to different outputs.

Anyway, thanks for responding. I like your idea of sticking with the visual aspect of the app. Nonetheless, the app is definitely fun to use for sure. :-)

**Comment by maximecb** [comment]
Thanks @wdevore :)
