### ISSUE TITLE
menu opens when knob drag/drop ends over empty space

### ISSUE THREAD

**Issue by khimaros** [maximecb/noisecraft#72]
reproduction steps:

1. click mouse + hold on a knob
2. drag the cursor onto an empty space of the canvas
3. release mouse button

what happens? menu opens

what should happen? nothing

**Comment by maximecb** [comment]
Hi @khimaros. Are you running Safari? If so, there's a bug in the Safari pointer capture API. If not, can you specify which browser and OS you're running?

**Comment by khimaros** [comment]
@maximecb

```
Name: Firefox
Version: 96.0.3
Build ID: 20220126154723
Distribution ID:
User Agent: Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
OS: Linux 5.16.0-1-amd64 #1 SMP PREEMPT Debian 5.16.7-2 (2022-02-09)
OS Theme: Adwaita-dark / Adwaita
Multiprocess Windows: 6/6
Fission Windows: 6/6 Enabled by phased rollout
Enterprise Policies: Inactive
Google Location Service Key: Found
Google Safebrowsing Key: Found
Mozilla Location Service Key: Found
Safe Mode: false
```

**Comment by maximecb** [comment]
Hm. That's disappointing. It used to work in Firefox. They must have changed the behavior of the pointer capture API.

Any chance you could help me investigate? The code that handles this is here: https://github.com/maximecb/noisecraft/blob/main/public/knob.js#L41

**Comment by maximecb** [comment]
I implemented a hack which I think should fix the problem. Let me know if it does/doesn't :)
