### ISSUE TITLE
ClockDiv not dividing time properly

### ISSUE THREAD

**Issue by treefrogman** [maximecb/noisecraft#85]
If I set up two sequencers, one on a Clock, the other on that same Clock passed through a ClockDiv, setting the ClockDiv to any ratio other than 1:1 will cause the downstream sequencer to move slower, but not the _right_ slower. Observe:
![image](https://user-images.githubusercontent.com/985484/168398950-0a9434ff-1fab-4c24-966d-6639d8310caf.png)
Now, if we slow this down, we can actually see on the Scopes what's going on:
![image](https://user-images.githubusercontent.com/985484/168399176-00283dc7-7e0f-4026-812c-08e7ffab1047.png) 3:1 ![image](https://user-images.githubusercontent.com/985484/168400105-2e05320d-4979-4332-8850-c9aa061b05c4.png) 4:1 ![image](https://user-images.githubusercontent.com/985484/168400199-757d7e92-aa71-40ea-99b6-3ce66d65110d.png)

A rising edge in the original wave triggers a rising edge in the divided wave. Good so far. Now we count `n` rising edges (including that first one), in this case two. Still good. The problem is that upon counting the last rising edge we don't immediately trigger a falling edge in the divided wave, but instead wait for a falling edge in the original wave.

We'll have to switch from watching for rising/falling edges to watching for... just... edges. So from the first edge, count `(n-1)*2` edges and put the next edge, repeat.

**Comment by treefrogman** [comment]
I guess I was overcomplicating it somehow. I'm playing with it right now and all I had to do was make it count every edge, not just rising, and that fixed it!

**Comment by maximecb** [comment]
Hey Miles.

Thanks for pointing this out. This seems like a real problem and so worth fixing. Slight issue that many already shared projects use the ClockDiv node 😅 , so I'd like to take inventory of how many and how badly they will be affected (hopefully they still sound good with this change). Will probably still apply the fix because it would be dumb to keep this in a broken state.

**Comment by maximecb** [comment]
I went through the projects using `ClockDiv` and I would say most of them still sound good with the new behavior, so I deployed the change 👍 

Of particular interest:
https://noisecraft.app/518
https://noisecraft.app/228
