### ISSUE TITLE
Scopes can't be pasted

### ISSUE THREAD

**Issue by treefrogman** [maximecb/noisecraft#93]
```
TypeError: unknown node property samples for Scope
    at validateNode (main.js:803:19)
    at new Paste (main.js:1023:9)
    at HTMLDocument.document.onpaste (main.js:4062:20)
```

**Comment by treefrogman** [comment]
Is this as simple as adding a `case "samples":` to [`validateParams`](https://github.com/maximecb/noisecraft/blob/6617d0e58775cdb64ce67cd8e1b56baf55089c0d/public/model.js#L621)?

**Comment by treefrogman** [comment]
Ah, no, I think we add `samples: [],` to the [NODE_SCHEMA['Scope']](https://github.com/maximecb/noisecraft/blob/6617d0e58775cdb64ce67cd8e1b56baf55089c0d/public/model.js#L351)

**Comment by maximecb** [comment]
Good catch. So the problem is that the samples shouldn't be copied.

I just deployed a fix, calling `resetState()` before serializing the copied data. Normally this happens when saving a project but wasn't done when copying nodes.
