### ISSUE TITLE
Can't share project with Opera browser

### ISSUE THREAD

**Issue by loatus** [maximecb/noisecraft#96]
Hi , thanks for your replies and apologies for not getting back to you sooner. I have been away from my computer while holidaying.

I have been unable to share any projects using the Opera browser but can share those same projects ok if I am using the Chrome browser instead. The Chrome browser does not seem to work for me though as the cables appear invisible. maybe there is some simple solution or setting I am not aware of.    ... thanks 

![image](https://user-images.githubusercontent.com/30633486/171674423-880482b6-a7e4-47db-9aca-c8d96652365c.png)

**Comment by loatus** [comment]
Regarding the projects with cables appearing invisible while using the Chrome browser... the projects are able to play and are audible .. so the cables must actually be there, just invisible. If I view those same projects via the Opera browser they are then visible

**Comment by maximecb** [comment]
Hi Daniel. I'm using Chrome on the regular as well (on a mac) and I don't have this problem, so not quite sure what's happening there. Are you on Windows, Linux?

Regarding the opera issue, I might need your help investigating/debugging this one.

**Comment by maximecb** [comment]
Okay, well if you ever get additional info about the issue with chrome on windows, let me know :)
