### ISSUE TITLE
MIDI channel

### ISSUE THREAD

**Issue by slowscape** [maximecb/noisecraft#98]
Is there any way to select the midi channel on the midi module?

Thanks!

**Comment by maximecb** [comment]
Hi @slowscape. Currently there isn't, but it might be pretty easy to implement so I could look into it :)

I'm assuming you have multiple midi controllers that you want to interface with? What does your setup look like?

**Comment by slowscape** [comment]
Hi @maximecb, I've actually been looking for the perfect companion to [ORCA](https://wiki.xxiivv.com/site/orca.html). ORCA is an interesting application for sending midi and sequencing, and can send on multiple channels. I really like it's workflow.

I also love working with modular synths, and yours is super straight forward. So your app is the best candidate so far minus the channel selection bit hehe

**Comment by maximecb** [comment]
Happy to hear you say that. The creator of ORCA and I are friends :)

I'll look into implementing midi channel selection in the next few days 👷‍♀️ 

I hope you create videos of some of your creations. Would be very curious to see what you make.

**Comment by maximecb** [comment]
Alright I just deployed the changes :)

You can now double-click on a `MidiIn` node and you'll see a `chanNo` field. The `null` value means accept input from any midi channel, but you can set a value between 1 and 16 to specify which MIDI channel you want the node to accept input from.

Please try it out and let me know if it works for you!

**Comment by maximecb** [comment]
I updated the /help page to mention the new `chanNo` setting as well.

Curious to see what you create with this, please post a video :)

**Comment by slowscape** [comment]
Oh wow, this is perfect! I'll come back here with whatever happens next ^_^

**Comment by maximecb** [comment]
> Oh wow, this is perfect! I'll come back here with whatever happens next ^_^

Please do! :) :) :)
